language: java
sudo: false
install: true

addons:
  sonarqube:
    token:
      secure: "09111523dbe766d338255106b15b844d1603d179"

jdk:
  - oraclejdk8

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

notifications:
  email: false